###Biblioteka NumPy

### Spis treści:
1. [Biblioteka NumPy - podstawowe informacje](#0)
2. [Ćwiczenia - biblioteka NumPy](#1)


### <a name='0'></a> 1. Biblioteka NumPy - podstawowe informacje

Biblioteka NumPy to podstawowe narzędzie stosu uczenia maszynowego z użyciem języka programowania Python.

Pozwala ona przeprowadzić efektywne operacje na strukturach danych, które są najczęściej wykorzystywane w uczeniu maszynowym: wektor, macierz, tensor.

Jako, że biblioteka NumPy jest jedną z najczęściej używanych bibliotek podczas pracy z danymi, w tym rozdziale przedstawione zostaną operacje NumPy najczęściej przeprowadzane podczas pracy wymagającej zastosowania uczenia maszynowego.


NumPy (*Numerical Python*) to popularna biblioteka w języku Python, która jest używana głównie do obliczeń numerycznych i manipulacji danymi w postaci tablic. Poniżej kilka kluczowych cech i zastosowań biblioteki NumPy:

1. Tablice NumPy: NumPy wprowadza typ danych tablicy n-wymiarowej (ndarray), który umożliwia efektywną i szybką pracę z wielowymiarowymi danymi numerycznymi. Te tablice są podobne do list, ale oferują znacznie większą wydajność i funkcjonalność.

2. Szybkość: NumPy jest napisane w języku C, co pozwala na wydajne obliczenia numeryczne. Dzięki temu jest idealne do przetwarzania dużych zbiorów danych i wykonywania zaawansowanych operacji matematycznych.

3. Funkcje matematyczne: NumPy zawiera wiele funkcji matematycznych, takich jak operacje arytmetyczne, funkcje trygonometryczne, operacje na macierzach i wiele innych, co czyni go potężnym narzędziem do analizy danych i obliczeń naukowych.

4. Indeksowanie i wycinanie: NumPy oferuje zaawansowane techniki indeksowania i wycinania tablic, co ułatwia dostęp do konkretnych danych w tablicach wielowymiarowych.

5. Operacje na tablicach: NumPy umożliwia wykonywanie operacji na całych tablicach bez potrzeby pętli. To pozwala na efektywne obliczenia na danych.

6. Integracja z innymi bibliotekami: NumPy jest często używane w połączeniu z innymi bibliotekami do analizy danych, takimi jak Pandas, Matplotlib do wizualizacji, czy SciPy do bardziej zaawansowanych obliczeń naukowych.

7. Wsparcie dla rozszerzeń: NumPy ma wiele rozszerzeń, takich jak NumPy-BLAS, które zapewniają jeszcze lepszą wydajność w obliczeniach numerycznych.



Dzięki tym cechom NumPy jest szeroko stosowane w dziedzinach takich jak analiza danych, uczenie maszynowe, inżynieria, nauki przyrodnicze i wiele innych, gdzie wymagane są obliczenia numeryczne na dużą skalę.

### <a name='1'></a> 2. Ćwiczenia - biblioteka NumPy

In [ ]:
import numpy as np
np.__version__

'1.26.4'

###Ćwiczenie 1

Sprawdź czy wszytskie elemnety tablic A, B, C oraz D zwracają wartość logiczną True.

Zwrócenie wartości logicznej True lub False dla każdego obiektu NumPy.

Jeżeli wszytskie elementy zwracają wartość logiczną True - cały obiekt zwróci wartość logiczną True.

Jeżeli chociaż jeden elemnet zwróci wartość logiczną False - cąły obiekt zwróci wartość logiczną False.

In [1]:
import numpy as np 

A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])


**Wskazówka**: użyj funkcji all().

In [5]:
import numpy as np

A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

print("czy a zawiera same true: ", A.all())

print("czy b zawiera same true: ", B.all())

print("czy c zawiera same true: ", C.all())

print("czy d zawiera same true: ", D.all())


czy a zawiera same true:  True
czy b zawiera same true:  False
czy c zawiera same true:  False
czy d zawiera same true:  True


###Ćwiczenie

Punkty do wykonania:

*   Załaduj moduł numpy
*   Utwórz i przypisz do zmiennej matrix jednowymiarową tablicę z elementami od 0 do 19.
 **Wskazówka** : Służy do tego metoda *np.arange()*

*   Wyświetl kształ tej tablicy. **Wskazówka** : Służy do tego właściwość *shape*
*   Wyświetl zerowy (index 0) i piąty element tablicy (index 4). **Wskazówka** : Korzystaj z [] i indeksowania od 0.

*   Zmień kształ tablicy na 2x10. Wynik przekształcenia zapisz do zmiennej new_matrix. Ponownie sprawdź kształ tablicy i wyświetl jej zawartość.
 **Wskazówka** : Skorzystaj z metody *reshape()*.
*   Wyświetl czwarty elemnet znajdujący się w zerowym wierszu tablicy new_matrix. Indeksując elementy w tablicach kilkuwymiarowych należy skorzystać z podwójnych nawiasów kwadratowych [][].

*   Polecenie:

  a_python_list =  [2**x for x in range(10)]

  tworzy standardową pythonową listę dziesięcu kolejnych potęg.
  W oparciu o tę listę utwórz obiekt numpy array i przypisz go do zmiennej special_matrix.

*   Utwórz tablicę zero_array skłądajacą się z 10 zer.
 **Wskazówka** : Skorzystaj z metody *zeros()*.

*   Utwórz tablice one_array skłądającą się z 10 jedynek, rozmieszczonych w 2 wierszach. **Wskazówka** : Skorzystaj z metody *ones()*.
*   Utwórz tablicę empty_array składajacą się ze 100 dowolnych liczb.
  **Wskazówka** : Skorzystaj z metody *empty()*.
Metoda *empty()* tworzy tablicę, która zawiera to, co akurat było w pamięci. Wielokrotne uruchamianie w/w polecenia może dawać różne wyniki, ale to nie jest jakiś świetny sposób na generowanie liczb losowych.
*   Utwórz tablicę lucky_array o wymiarach 5x5 składajacą się z samych trzynastek. **Wskazówka** : Skorzystaj z metody *full()*.
*   Utwórz tablicę diagonal_array o wymiarach 5x5, ktora na przekątnej ma jedynki, a pozozstałe wartości to zera.
  
  **Wskazówka** : Skorzystaj z metody *eye()*.

*   Utwórz tablicę random_array składajacą się z 10 losowych liczb.
 **Wskazówka** : Skorzystaj z metody *random.random()*.


















In [7]:
import numpy as np

matrix = np.arange(20)

print(f"kształt: {matrix.shape}")
print(f"elementy (index 0 i 4): {matrix[0], {matrix[4]}}")

new_matrix = matrix.reshape(2, 10)
print(f"nowy kształt: {new_matrix.shape}")

print(f"element [0][3]: {new_matrix[0, 3]}")

a_python_list = [2**x for x in range(10)]
special_matrix = np.array(a_python_list)
print("special_matrix:\n", special_matrix)

# tablica z 10 zerami 
zero_array = np.zeros(10)
print("\nzero_array:\n", zero_array)

# tablica z 10 jedynkami, 2 wiersze 
one_array = np.ones((2, 5))
print("\nnone_array:\n", one_array)

# pusta tablica 100 elementów 
empty_array = np.empty(100)
print("\nkształt empty_arrat:", empty_array.shape)

# tablica 5x5 z samymi 13
lucky_array = np.full((5, 5), 13)
print("\nlucky_array\n", lucky_array)

# macierz tożsamościowa 
diagonal_array = np.eye(5)
print("\ndigital_array:\n", diagonal_array)

# tablica 10 losowych zmiennoprzecinkowych 
random_array = np.random.random(10)
print("\nrandom_array:\n", random_array)




kształt: (20,)
elementy (index 0 i 4): (np.int64(0), {np.int64(4)})
nowy kształt: (2, 10)
element [0][3]: 3
special_matrix:
 [  1   2   4   8  16  32  64 128 256 512]

zero_array:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

none_array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

kształt empty_arrat: (100,)

lucky_array
 [[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]

digital_array:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

random_array:
 [0.74676827 0.21760727 0.93174544 0.7196963  0.66410023 0.04176174
 0.52864101 0.83431195 0.57184386 0.19854094]


###Jeszcze więcej ćwiczeń z NumPy

Punkty do wykonania:

Biblioteka scikit-learn zawiera wiele użytecznych narzędzi przygotowujących dane do procesu machine learning.

Zaprezentowane laboratorium ma jednak pokazać, że bez biblioteki scikit-learn jesteśmy w stanie doskonale sobie poradzić.
Naszym celem będzie również utrwalenie informacji odnosnie podziału danych na uczace i testowe oraz na znane cechy próbek i przewidywaną wartość target.

*   Zaimportuj moduł numpy
*   Utwórz tablicę matrix zawierającą nieparzyste liczby od 5 do 29.
 **Wskazówka** : Skorzystaj z metody *arange()*.
*   Utwórz tablicę boolMatrix zawierającą tylko wartości True/ False.
True, gdy na odpowiedniej pozycji w boolMatrix znajduje się element < 10, a False w przeciwnym wypadku.
*   Wyświetl tylko te pozycje z tablicy matrix, które spełniają warunek:
 -- Na odpowiedniej pozcyji boolMatrix znanjduje się wartość True.
 Wartość pozycji jest < 20.
 (Warunek może być bezpośrednio zapisany w []).

*   Wartość pozycji jest podzielna przez 3.
 **Wskazówka** : Warunek logiczny powinien sprawdzać czy reszta z dzielenia pozycji tablicy jest przez 3 jest równa 0.








In [5]:
import numpy as np

matrix = np.arange(5, 30, 2)

boolMatrix = matrix < 10

print(f"elementy < 10: {matrix[boolMatrix]}")

filtered = matrix[(matrix < 20) & (matrix % 3 == 0)]
print(f"elementy < 20 i podzielone przez 3: {filtered}")

elementy < 10: [5 7 9]
elementy < 20 i podzielone przez 3: [ 9 15]


###Generujemy macierz

###Określamy warunek - do nowej zmiennej boolMatrix przypisujemy True/ False jeżeli dany element macierzy matrix spełnia lub nie warunek < 10.

###Wyswietli jedyne te wartości, które spełniają warunek

###Wyświetlamy kolejne elemnty tablicy matrix spełniajace warunek

### Ćwiczenie - Ręczny podział danych na uczące i testowe

Punkty do wykonania:

*   Do zmiennej matrix zapisz tablicę 50-elementową, o wymiarach 10x5.
*   "Półautomatyczne cięcie zbioru danych na dane uczące (train data) i testowe (test data)" - wykonaj podany fragment kodu.
*   Zbuduj wyrażenia zawierające:

 -- Wiersze od poczatku do split_border i wszytskie kolumny
 (**Wskazówka** : wartość split_border - to liczba float. Zaokrąglij ją więc do liczby całkowitej. Podczas budowania slice uzyj funkcji *round()*.)
 -- Wiersze od split_border do końca i wszytskie kolumny
 (**Wskazówka** : wartość split_border - to liczba float. Zaokrąglij ją więc do liczby całkowitej. Podczas budowania slice uzyj funkcji *round()*.)





In [ ]:
import numpy as np

In [ ]:
matrix = np.arange(50).reshape(10, 5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
print(matrix.shape)
num_rows = matrix.shape[0]
print(num_rows)
num_columns = matrix.shape[1]
print(num_columns)

(10, 5)
10
5


Dzielenie tablicy na 20% i 80%.

In [ ]:
split_level = 0.2
num_rows = matrix.shape[0]
split_border = split_level * num_rows

In [ ]:
first_part_of_data = matrix[:round(split_border), :]
first_part_of_data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
second_part_of_data = matrix[round(split_border): , :]
second_part_of_data

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

###Jako, że nasze dane są mało losowe - wymieszajmy wiersze.

In [ ]:
np.random.shuffle(matrix)

###Powtórzmy dzielenie tablicy na 20% i 80%.

In [ ]:
split_level = 0.2
num_rows = matrix.shape[0]
split_border = split_level * num_rows

In [ ]:
first_part_of_data = matrix[:round(split_border), :]
first_part_of_data

array([[40, 41, 42, 43, 44],
       [30, 31, 32, 33, 34]])

In [ ]:
second_part_of_data = matrix[round(split_border): , :]
second_part_of_data

array([[45, 46, 47, 48, 49],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [ 5,  6,  7,  8,  9],
       [35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

Punkty do wykonania:

*   Napisz kod, który dzieli dane na uczące i testowe oraz rozdziela je na zbiór feature i zbiór target.

Ostateczne oznaczenia:

-- X_train 80% danych - wszytskie kolumny oprócz ostatniej

-- X_test 20% danych - wszytskie kolumny oprócz ostatniej

-- y_train 80% danych - ostatnia kolumna

-- y_test 20% danych - ostatnia kolumna

###Dane:

In [ ]:
data = np.arange(500).reshape(100, 5)

In [ ]:
data

array([[295, 296, 297, 298, 299],
       [135, 136, 137, 138, 139],
       [ 30,  31,  32,  33,  34],
       [405, 406, 407, 408, 409],
       [235, 236, 237, 238, 239],
       [460, 461, 462, 463, 464],
       [ 25,  26,  27,  28,  29],
       [455, 456, 457, 458, 459],
       [180, 181, 182, 183, 184],
       [465, 466, 467, 468, 469],
       [400, 401, 402, 403, 404],
       [105, 106, 107, 108, 109],
       [140, 141, 142, 143, 144],
       [165, 166, 167, 168, 169],
       [470, 471, 472, 473, 474],
       [215, 216, 217, 218, 219],
       [325, 326, 327, 328, 329],
       [230, 231, 232, 233, 234],
       [205, 206, 207, 208, 209],
       [ 20,  21,  22,  23,  24],
       [110, 111, 112, 113, 114],
       [430, 431, 432, 433, 434],
       [ 90,  91,  92,  93,  94],
       [ 50,  51,  52,  53,  54],
       [255, 256, 257, 258, 259],
       [495, 496, 497, 498, 499],
       [320, 321, 322, 323, 324],
       [365, 366, 367, 368, 369],
       [475, 476, 477, 478, 479],
       [ 55,  

In [ ]:
data.shape

(100, 5)

###Trzetasuj dane aby zostały ułożone "losowo"

In [ ]:
np.random.shuffle(data)

###Wyznacz nową wartość split_border, która określa ile wierszy będzie wziętych do danych treningowych, a ile do danych testowych

In [ ]:
split_level = 0.8
num_rows = data.shape[0]
split_border = split_level * num_rows

###Wyznacz X_train - wiersze od początku do split_border, kolumny - wszystkie, poza ostatnią.

In [ ]:
X_train = data[:round(split_border), :-1]
X_train

array([[295, 296, 297, 298],
       [135, 136, 137, 138],
       [ 30,  31,  32,  33],
       [405, 406, 407, 408],
       [235, 236, 237, 238],
       [460, 461, 462, 463],
       [ 25,  26,  27,  28],
       [455, 456, 457, 458],
       [180, 181, 182, 183],
       [465, 466, 467, 468],
       [400, 401, 402, 403],
       [105, 106, 107, 108],
       [140, 141, 142, 143],
       [165, 166, 167, 168],
       [470, 471, 472, 473],
       [215, 216, 217, 218],
       [325, 326, 327, 328],
       [230, 231, 232, 233],
       [205, 206, 207, 208],
       [ 20,  21,  22,  23],
       [110, 111, 112, 113],
       [430, 431, 432, 433],
       [ 90,  91,  92,  93],
       [ 50,  51,  52,  53],
       [255, 256, 257, 258],
       [495, 496, 497, 498],
       [320, 321, 322, 323],
       [365, 366, 367, 368],
       [475, 476, 477, 478],
       [ 55,  56,  57,  58],
       [485, 486, 487, 488],
       [145, 146, 147, 148],
       [420, 421, 422, 423],
       [450, 451, 452, 453],
       [375, 3

In [ ]:
X_train.shape

(80, 4)

In [ ]:
X_test = data[round(split_border): , :-1]
X_test

array([[225, 226, 227, 228],
       [280, 281, 282, 283],
       [275, 276, 277, 278],
       [300, 301, 302, 303],
       [195, 196, 197, 198],
       [445, 446, 447, 448],
       [310, 311, 312, 313],
       [265, 266, 267, 268],
       [435, 436, 437, 438],
       [ 10,  11,  12,  13],
       [285, 286, 287, 288],
       [330, 331, 332, 333],
       [200, 201, 202, 203],
       [ 45,  46,  47,  48],
       [380, 381, 382, 383],
       [125, 126, 127, 128],
       [390, 391, 392, 393],
       [425, 426, 427, 428],
       [315, 316, 317, 318],
       [210, 211, 212, 213]])

In [ ]:
X_test.shape

(20, 4)

In [ ]:
y_train = data[:round(split_border), -1:]
y_train

array([[299],
       [139],
       [ 34],
       [409],
       [239],
       [464],
       [ 29],
       [459],
       [184],
       [469],
       [404],
       [109],
       [144],
       [169],
       [474],
       [219],
       [329],
       [234],
       [209],
       [ 24],
       [114],
       [434],
       [ 94],
       [ 54],
       [259],
       [499],
       [324],
       [369],
       [479],
       [ 59],
       [489],
       [149],
       [424],
       [454],
       [379],
       [364],
       [ 79],
       [154],
       [359],
       [  9],
       [344],
       [349],
       [159],
       [164],
       [399],
       [  4],
       [494],
       [ 74],
       [ 84],
       [104],
       [254],
       [264],
       [ 89],
       [ 19],
       [224],
       [294],
       [189],
       [174],
       [354],
       [124],
       [ 44],
       [ 99],
       [309],
       [389],
       [ 39],
       [339],
       [179],
       [244],
       [134],
       [444],
       [414],
      

In [ ]:
y_train.shape

(80, 1)

In [ ]:
y_test = data[round(split_border): , -1:]
y_test

array([[229],
       [284],
       [279],
       [304],
       [199],
       [449],
       [314],
       [269],
       [439],
       [ 14],
       [289],
       [334],
       [204],
       [ 49],
       [384],
       [129],
       [394],
       [429],
       [319],
       [214]])

###Funkcja wbudowana z modułu sklearn

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data[:, :-1], data[:, -1], test_size=0.2, shuffle=True)

###Ćwiczenie

Polecenia do wykonania:

*   W zmiennej X zapisz tablicę dwuwymiarową z kolejnymi liczbami od 1 do 25.
 **Wskazówka** : skorzystaj z metod arrange() i reshape().

*   W zmiennej Ones zapisz tablicę o takim samym kształcie jak X, z tym że całą wypełniona jedynkami.**Wskazówka** : skorzystaj z metody ones().

*   Pomnóż przez siebie macierz X oraz Ones. **Wskazówka** : skorzystaj z metody dot().
*   W algebrze liniowej elementem neutralnym macierzy jest macierz zer, wypełniona jedynkami na przekątnej.

- Do zmiennej diag zapisz macierz o takich wymiarach jak X, wypełnioną samymi zerami. **Wskazówka** : skorzystaj z metody zeros().
- Wypełnij diag jedynkami na przekątnej. **Wskazówka** : skorzystaj z metody fill_diagonal().
-Pomnóż przez siebie X i diag i sprawdź czy wynik to X. Wnioski?

-Wyświetl tablicę o wymiarach takich jak X, gdzie (we wszystkich punktach skorzystaj w where):

-Występują tylko jedynki i zera. Jedynki mają się pojawić tam, gdzie w X występuje wartość większa od 10, a zera w pozostałych przypadkach.

-Występują tylko jedynki i zera. Jedynki mają się pojawić tam, gdzie występuje wartość parzysta, a zero w pozostałych przypadkach.

* Utworz tablicę X_bis wyznaczoną w następujący sposób. Dla wartości w X większych od 10 zwrócona zostanie wartość 2 razy większa, a dla pozostałych 0.
Policz ile jest elementów niezerowych w X_bis.
 **Wskazówka** : skorzystaj z metody count_nonzero()

* Oto dwie tablice:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])

* Dodaj (doklej) do tablicy x tablicę y jako nową kolumnę.
 **Wskazówka** : skorzystaj z metody append() z parametrem axis=1
* Dodaj (doklej) do tablicy x tablicę y jako nowy wiersz.
 **Wskazówka** : skorzystaj z metody append() z parametrem axis=0





In [8]:
import numpy as np

X = np.arange(1, 26).reshape(5, 5)
Ones = np.ones(X.shape)

print("macierz X:\n", X)
print("\nMacierz ones:\n", Ones)

X_dot_Ones = np.dot(X, Ones) 
print("\nMnożenie X i Ones:\n", X_dot_Ones)

diag = np.zeros(X.shape)
np.fill_diagonal(diag, 1)

X_dot_diag = np.dot(X, diag)
print("\nMnożenie X i diag:\n", X_dot_diag)

where_10 = np.where(X > 10, 1, 0)
print("\n1 tam gdzie > 10, resta 0:\n:", where_10)

where_even = np.where(X % 2 == 0, 1, 0)
print("\n1 tam gdzie parzysste, reszta 0:\n", where_even)

X_bis = np.where(X > 10, 2 * X, 0)
print("\nX_bis (x2 gdy > 10, reszta 0)\n", X_bis)
print("liczba elementow niezerowych w X_bis:", np.count_nonzero(X_bis))

x = np.array([[10, 20, 30], [40, 50, 60]])
y = np.array([[100], [200]])

x_append_col = np.append(x, y, axis=1)
print("\nx z doklejoną kolumną y:\n", x_append_col)

y_row = np.array([[70, 80, 90]])
x_append_row = np.append(x, y_row, axis=0)
print("\nx z doklejonym wierszem y_row:\n", x_append_row)


macierz X:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Macierz ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Mnożenie X i Ones:
 [[ 15.  15.  15.  15.  15.]
 [ 40.  40.  40.  40.  40.]
 [ 65.  65.  65.  65.  65.]
 [ 90.  90.  90.  90.  90.]
 [115. 115. 115. 115. 115.]]

Mnożenie X i diag:
 [[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]

1 tam gdzie > 10, resta 0:
: [[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

1 tam gdzie parzysste, reszta 0:
 [[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]

X_bis (x2 gdy > 10, reszta 0)
 [[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]
liczba elementow niezerowych w X_bis: 15

x z doklejoną kolumną y:
 [[ 10  20  30 100]
 [ 40  50  60 200]]

x z doklejonym wierszem y_row:
 [[10 20 30]
 [40 50 60]
 [70 80